/**
 * Tolerant YAML-frontmatter parsing/serialization for wiki pages.
 *
 * Cards are generated by LLMs, so the parser mirrors llm_wiki's lenient
 * stance: stray ```yaml fences, a leading `frontmatter:` key, a missing
 * opening `---`, inline wikilink lists without brackets, and CRLF are all
 * repaired rather than rejected. The serializer emits the strict canonical
 * form the llm_wiki ingest prompt demands (first line `---`, inline arrays,
 * bare slug lists for related).
 * @module dsh-knowledge-cards/core/frontmatter
 */
export interface ParsedFrontmatter {
    frontmatter: Record<string, unknown> | null;
    /** Body markdown, with the frontmatter block removed. */
    body: string;
}
/**
 * Parse a wiki page's YAML frontmatter. Returns null frontmatter when no
 * frontmatter block is found (the whole content is treated as body).
 */
export declare function parseFrontmatter(content: string): ParsedFrontmatter;
/**
 * Serialize frontmatter to the canonical block form (opening `---`, key: value
 * lines, closing `---`), followed by a blank line and the body.
 */
export declare function serializePage(frontmatter: Record<string, unknown>, body: string): string;
/** Extract the title from a filename stem (kebab → Title Case for display). */
export declare function slugFromTitle(title: string): string;
//# sourceMappingURL=frontmatter.d.ts.map