/**
 * Tolerant YAML-frontmatter parsing/serialization for wiki pages.
 *
 * Cards are generated by LLMs, so the parser mirrors llm_wiki's lenient
 * stance: stray ```yaml fences, a leading `frontmatter:` key, a missing
 * opening `---`, inline wikilink lists without brackets, and CRLF are all
 * repaired rather than rejected. The serializer emits the strict canonical
 * form the llm_wiki ingest prompt demands (first line `---`, inline arrays,
 * bare slug lists for related).
 * @module dsh-knowledge-cards/core/frontmatter
 */
const OPEN = '---';
function stripCodeFence(text) {
    // ```yaml\n---\n...\n---\n``` → ---\n...\n---
    return text.replace(/^```(?:yaml|yml)?\s*\r?\n/, '').replace(/\r?\n```\s*$/, '');
}
function stripFrontmatterKey(text) {
    // A stray `frontmatter:` line before the real fence (LLM corruption).
    return text.replace(/^frontmatter:\s*\r?\n/i, '');
}
/** Locate the frontmatter block (lenient: may lack the opening fence). */
function locate(text) {
    // Fast path: strict top-of-file fence.
    if (text.startsWith(OPEN)) {
        const end = text.indexOf('\n---', 3);
        if (end !== -1) {
            const fenceEnd = text.indexOf('\n', end + 1);
            const bodyStart = fenceEnd === -1 ? text.length : fenceEnd + 1;
            return { block: text.slice(0, bodyStart), bodyStart };
        }
        return null;
    }
    // Lenient: a leading junk line (```yaml / frontmatter:) then the fence.
    const cleaned = stripCodeFence(stripFrontmatterKey(text));
    if (cleaned !== text) {
        const inner = locate(cleaned);
        if (inner !== null)
            return inner;
    }
    // Lenient: the opening fence is missing but the payload starts with a
    // `key: value` line and a closing `---` fence exists (LLM corruption the
    // llm_wiki sanitizer repairs too).
    const firstLine = text.slice(0, text.indexOf('\n') === -1 ? text.length : text.indexOf('\n'));
    if (/^[A-Za-z_][\w-]*\s*:/.test(firstLine.trim())) {
        const end = text.indexOf('\n---', 1);
        if (end !== -1) {
            const fenceEnd = text.indexOf('\n', end + 1);
            const bodyStart = fenceEnd === -1 ? text.length : fenceEnd + 1;
            return { block: text.slice(0, bodyStart), bodyStart };
        }
    }
    return null;
}
function parseScalar(raw) {
    const value = raw.trim();
    if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
        return value.slice(1, -1).replace(/\\"/g, '"');
    }
    if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
        return value.slice(1, -1);
    }
    if (value === 'true')
        return true;
    if (value === 'false')
        return false;
    if (value === 'null' || value === '~' || value === '')
        return '';
    if (/^-?\d+$/.test(value))
        return Number(value);
    return value;
}
function parseArray(raw) {
    const inner = raw.trim();
    if (inner.startsWith('[') && inner.endsWith(']')) {
        const body = inner.slice(1, -1).trim();
        if (body === '')
            return [];
        return splitTopLevel(body).map((item) => {
            const trimmed = item.trim();
            // Repair `[[a]], [[b]]` → bare `a`, `b` (invalid YAML llm_wiki repairs too).
            const bare = trimmed.replace(/^\[\[|\]\]$/g, '');
            return parseScalar(bare);
        });
    }
    return [];
}
/** Split `a, b, "c, d"` respecting quotes (top-level commas only). */
function splitTopLevel(text) {
    const parts = [];
    let current = '';
    let quote = null;
    for (const char of text) {
        if (quote !== null) {
            current += char;
            if (char === quote)
                quote = null;
        }
        else if (char === '"' || char === "'") {
            quote = char;
            current += char;
        }
        else if (char === ',') {
            parts.push(current);
            current = '';
        }
        else {
            current += char;
        }
    }
    parts.push(current);
    return parts;
}
function normalizeKey(key) {
    return key.trim().replace(/^["']|["']$/g, '');
}
function blockToArray(lines, index) {
    const items = [];
    let cursor = index;
    while (cursor < lines.length) {
        const line = lines[cursor];
        if (/^\s*-\s+/.test(line)) {
            items.push(parseScalar(line.replace(/^\s*-\s+/, '').trim()));
            cursor += 1;
        }
        else if (line.trim() === '-') {
            cursor += 1;
        }
        else {
            break;
        }
    }
    return { value: items, next: cursor };
}
/**
 * Parse a wiki page's YAML frontmatter. Returns null frontmatter when no
 * frontmatter block is found (the whole content is treated as body).
 */
export function parseFrontmatter(content) {
    const located = locate(content);
    if (located === null)
        return { frontmatter: null, body: content };
    const block = located.block;
    const body = content.slice(located.bodyStart);
    const lines = block.replace(/\r\n/g, '\n').split('\n');
    // Strip the fences.
    const first = lines[0]?.trim();
    if (first !== OPEN) {
        // Lenient repair: opening fence missing → treat the junk line as part of
        // the payload only if it looks like a key: value pair.
        if (!/^[A-Za-z_][\w-]*\s*:/.test(first ?? '')) {
            return { frontmatter: null, body: content };
        }
    }
    const payload = lines.filter((line) => line.trim() !== OPEN && line.trim() !== '');
    const frontmatter = {};
    let cursor = 0;
    while (cursor < payload.length) {
        const line = payload[cursor];
        if (/^\s*-\s+/.test(line)) {
            cursor += 1;
            continue;
        }
        const match = /^([A-Za-z_][\w-]*)\s*:\s*(.*)$/.exec(line);
        if (match === null) {
            cursor += 1;
            continue;
        }
        const key = normalizeKey(match[1]);
        const rest = match[2].trim();
        if (rest === '') {
            // Block list (or empty).
            const { value, next } = blockToArray(payload, cursor + 1);
            frontmatter[key] = next > cursor + 1 ? value : [];
            cursor = next;
        }
        else if (rest.startsWith('[')) {
            frontmatter[key] = parseArray(rest);
            cursor += 1;
        }
        else {
            frontmatter[key] = parseScalar(rest);
            cursor += 1;
        }
    }
    return { frontmatter, body };
}
/** Quote a scalar for YAML output when needed. */
function quoteValue(value) {
    if (typeof value === 'number')
        return String(value);
    if (typeof value === 'boolean')
        return value ? 'true' : 'false';
    const text = String(value);
    if (text === '')
        return '""';
    if (/^[\w\u4e00-\u9fff-]+$/.test(text))
        return text;
    return JSON.stringify(text);
}
/** Render one frontmatter key with an inline array. */
function renderArray(values) {
    return '[' + values.map((value) => quoteValue(value)).join(', ') + ']';
}
/**
 * Serialize frontmatter to the canonical block form (opening `---`, key: value
 * lines, closing `---`), followed by a blank line and the body.
 */
export function serializePage(frontmatter, body) {
    const lines = [OPEN];
    for (const [key, value] of Object.entries(frontmatter)) {
        if (Array.isArray(value)) {
            if (value.length === 0) {
                lines.push(`${key}: []`);
            }
            else {
                lines.push(`${key}: ${renderArray(value)}`);
            }
        }
        else if (value === undefined || value === null || value === '') {
            lines.push(`${key}: ""`);
        }
        else {
            lines.push(`${key}: ${quoteValue(value)}`);
        }
    }
    lines.push(OPEN);
    const block = lines.join('\n');
    const trimmedBody = body.replace(/^\s*\n/, '');
    return `${block}\n\n${trimmedBody}${trimmedBody.endsWith('\n') ? '' : '\n'}`;
}
/** Extract the title from a filename stem (kebab → Title Case for display). */
export function slugFromTitle(title) {
    const slug = title
        .trim()
        .replace(/\s+/g, '-')
        .replace(/[^\w\u4e00-\u9fff-]/g, '')
        .replace(/-+/g, '-')
        .replace(/^-+|-+$/g, '');
    return slug === '' ? 'untitled' : slug;
}
